name: CI

on: 
  push:
    branches: 
    - main
  pull_request:
    branches: 
    - main

jobs:
  macos:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: SPM build
      run: swift build

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - swift:5.4
          - swift:5.5
          - swift:5.6
    container:
      image: ${{ matrix.image }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: swift build
